services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
      # Ony build development stage from dockerfile
      target: development

    # Mount our host dir to the docker container
    # Mount backend dir to (./backend) to (:) docker container (/src/app) 
    # Reflect File changes from host to c ontainer
    volumes:
      - ./backend:/src/app
      - ./src/app/node_modules

    # RUN in debug mode: npm start:debug --> Also start your vscode debugger
    # RUN in dev mode: npm run start:dev
    command: npm run start:dev
    depends_on:
      - postgres
    environment:
      # DATABASE_URL: postgres://user:password@postgres:5432/db
      # NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 9229:9229 # for debug
      

  frontend:
    build: 
      dockerfile: Dockerfile
      context: ./frontend
      target: development
    command: npm run serve
    volumes:
     - ./frontend:/frontend/src/app
     - ./frontend/src/app/node_modules
    ports:
      - 4200:4200
    links: 
      - backend

  postgres:
    image: postgres:10.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: db
    ports:
      - 35000:5432

  postgres_admin:
    image: dpage/pgadmin4:6.8
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80